const issueData = {
  largeCent: {
    id: '1',
    title: 'Large Cent',
    startDate: '1794',
    endDate: '2018',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/1794_1C_%27Venus_Marina%27_%28S-32%29_%28obv%29.jpg/400px-1794_1C_%27Venus_Marina%27_%28S-32%29_%28obv%29.jpg',
    body: `<p>The United States large cent was a coin with a face value of 1/100 of a United States dollar. Its nominal diameter was 1​1⁄8 inch (28.57 mm). The first official mintage of the large cent was in 1793, and its production continued until 1857, when it was officially replaced by the modern-size one-cent coin (commonly called the penny).</p><p>Large cents were made of nearly pure copper, or copper as pure as it emerged from smelting, without any deliberate addition of other metals (such as occurs in bronze).</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Large_cent'
  },
  halfCent: {
    id: '2',
    title: 'Half Cent',
    startDate: '1793',
    endDate: '1857',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Half_cent_obv.jpg/300px-Half_cent_obv.jpg',
    body: `<p>The half cent is the smallest denomination of United States coin ever minted. It was first minted in 1793 and last minted in 1857. It was minted in five different appearances.</p><p>First authorized by the Coinage Act of 1792 on April 2, 1792, the coin was produced in the United States from 1793 to 1857. The half-cent piece was made of 100% copper and was valued at five milles, or one two-hundredth of a dollar. It was slightly smaller than a modern U.S. quarter with diameters 22 mm (1793), 23.5 mm (1794–1836) and 23 mm (1840–1857). Coinage was discontinued by the Coinage Act of February 21, 1857. They were all produced at the Philadelphia Mint.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Half_cent_(United_States_coin)',
  },
  indianHeadCent: {
    id: '3',
    title: 'Indian Head Cent',
    startDate: '1859',
    endDate: '1909',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NNC-US-1859-1C-Indian_Head_Cent_%28wreath%29.jpg/950px-NNC-US-1859-1C-Indian_Head_Cent_%28wreath%29.jpg',
    body: `<p>From 1793 to 1857, the cent was a copper coin about the size of a half dollar. The discovery of gold in California caused a large inflation in prices. As gold became more abundant, the price of copper rose. Cent and half-cent manufacture was one of the only profit centers for the Mint and by 1850 the Mint began looking for alternatives. In 1857 the Mint reduced the size of the cent and changed the composition to 12% nickel and 88% copper (Copper-nickel), issuing a new design, the Flying Eagle cent. The new pieces were identical in diameter to modern cents, though thicker. This was the first used of copper-nickel by the United States. The copper-nickel made them look brighter and they began to be called "White cent" or "Nicks".</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Indian_Head_cent',
  },
  lincolnCent: {
    id: '4',
    title: 'Lincoln Cent',
    startDate: '1909',
    endDate: 'Present',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/US_One_Cent_Obv.png/440px-US_One_Cent_Obv.png',
    body: `<p>The Lincoln cent (or sometimes called Lincoln penny) is a one-cent coin that has been struck by the United States Mint since 1909. The obverse or heads side was designed by Victor David Brenner, as was the original reverse. The coin has seen several reverse, or tails, designs and now bears one by Lyndall Bass depicting a Union shield. All coins struck by the United States government with a value of 1/100 of a dollar are called cents because the United States has always minted coins using decimals. The penny nickname is a carryover from the coins struck in England, which went to decimals for coins in 1971.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Lincoln_cent',
  },
  twoCent: {
    id: '5',
    title: 'Two Cent Piece',
    startDate: '1864',
    endDate: '1872',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/1865_Two_Cent_Obverse.png/440px-1865_Two_Cent_Obverse.png',
    body: `<p>The two-cent piece was produced by the Mint of the United States for circulation from 1864 to 1872 and for collectors in 1873. Designed by James B. Longacre, there were decreasing mintages each year, as other minor coins such as the nickel proved more popular. It was abolished by the Mint Act of 1873.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Two-cent_piece_(United_States)',
  },
  threeCentSilver: {
    id: '6',
    title: 'Three Cent Silver',
    startDate: '1851',
    endDate: '1872',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/1851-O_3CS_%28obv%29.jpg/440px-1851-O_3CS_%28obv%29.jpg',
    body: `<p>The three-cent silver, also known as the three-cent piece in silver or trime, was struck by the Mint of the United States for circulation from 1851 to 1872, and as a proof coin in 1873. Designed by the Mint's chief engraver, James B. Longacre, it circulated well while other silver coinage was being hoarded and melted, but once that problem was addressed, became less used. It was abolished by Congress with the Coinage Act of 1873.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Three-cent_silver',
  },
  threeCentCopper: {
    id: '7',
    title: 'Three Cent Copper (Nickel)',
    startDate: '1865',
    endDate: '1889',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/NNC-US-1865-3C-Three-Cent%2C_Nickel.jpg/950px-NNC-US-1865-3C-Three-Cent%2C_Nickel.jpg',
    body: `<p>The copper-nickel three-cent piece, often called a three-cent nickel piece or three-cent nickel, was designed by US Mint Chief Engraver James B. Longacre and struck by the United States Bureau of the Mint from 1865 to 1889. It was initially popular, but its place in commerce was supplanted by the five-cent piece, or nickel.</p><p>With precious metal federal coinage hoarded during the economic turmoil of the American Civil War, including the silver three-cent piece, and even the copper-nickel cent commanding a premium, Congress issued paper money in denominations as small as three cents to replace the hoarded coins in commerce. These small slips of paper became ragged and dirty, and the public came to hate "shinplasters". After the issuance in 1864 of a lighter bronze cent and a two-cent piece of that metal, both of which circulated freely, there were proposals for a three-cent piece in copper-nickel to replace the three-cent note.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Three-cent_nickel',
  },
  olderNickels: {
    id: '8',
    title: 'Half Dimes',
    startDate: '1792/1794',
    endDate: '1873',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2b/1794_half_dime_obv.jpg',
    body: `<p>Some numismatists consider the denomination to be the first coin minted by the United States Mint under the Coinage Act of 1792, with production beginning on or about July 1792. However, others consider the 1792 half dime to be nothing more than a pattern coin, or 'test piece', and this matter continues to be subject to debate.</p><p>These coins were much smaller than dimes in diameter and thickness, appearing to be "half dimes". In the 1860s, powerful nickel interests successfully lobbied for the creation of new coins, which would be made of a copper-nickel alloy; production of such coins began in 1865, and were struck in two denominations — three and five cents (the latter introduced in 1866).</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Half_dime',
  },
  seatedLibertyNickels: {
    id: '9',
    title: 'Seated Liberty Half Dime',
    startDate: '1837',
    endDate: '1873',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/NNC-US-1839-O-5C-Seated_Liberty_%28no_drapery%29.jpg/550px-NNC-US-1839-O-5C-Seated_Liberty_%28no_drapery%29.jpg',
    body: `<p>These were the last silver half dimes produced. The design features Liberty seated on a rock and holding a shield and was first conceived in 1835 used first on the silver dollar patterns of 1836. The series is divided into several subtypes. The first was struck at Philadelphia in 1837 and New Orleans in 1838 and lacks stars on the obverse. In 1838 a semicircle of 13 stars was added around the obverse border, and this basic design was used through 1859. In 1853, small arrows were added to each side of the date to reflect a reduction in weight due to rising silver prices, and the arrows remained in place through 1855.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Half_dime#Seated_Liberty_(various_subtypes)_1837%E2%80%931873',
  },
  shieldNickels: {
    id: '10',
    title: 'Shield Nickel',
    startDate: '1866',
    endDate: '1883',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Shield_nickel_obverse_by_Howard_Spindel.png/440px-Shield_nickel_obverse_by_Howard_Spindel.png',
    body: `<p>The Shield nickel was the first United States five-cent piece to be made out of copper-nickel, the same alloy of which American nickels are struck today. Designed by James B. Longacre, the coin was issued from 1866 until 1883, when it was replaced by the Liberty Head nickel. The coin takes its name from the motif on its obverse, and was the first five-cent coin referred to as a "nickel"—silver pieces of that denomination had been known as half dimes.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Shield_nickel',
  },
  libertyNickels: {
    id: '11',
    title: 'Liberty Head (V) Nickel',
    startDate: '1883',
    endDate: '1913',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/NNC-US-1883-5C-Liberty_Nickel_%28no_cents%29.jpg/950px-NNC-US-1883-5C-Liberty_Nickel_%28no_cents%29.jpg',
    body: `<p>The Liberty Head nickel, sometimes referred to as the V nickel because of its reverse (or tails) design, is an American five-cent piece. It was struck for circulation from 1883 until 1912, with at least five pieces being surreptitiously struck dated 1913. The obverse features a left-facing image of the goddess of Liberty.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Liberty_Head_nickel',
  },
  buffaloNickels: {
    id: '12',
    title: 'Buffalo Nickel',
    startDate: '1913',
    endDate: '1938',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/NNC-US-1913-5C-Buffalo_Nickel_%28TyI-mound%29.jpg/950px-NNC-US-1913-5C-Buffalo_Nickel_%28TyI-mound%29.jpg',
    body: `<p>As part of a drive to beautify the coinage, five denominations of US coins had received new designs between 1907 and 1909. In 1911, Taft administration officials decided to replace Charles E. Barber's Liberty Head design for the nickel, and commissioned Fraser to do the work. They were impressed by Fraser's designs showing a Native American and an American bison. The designs were approved in 1912, but were delayed several months because of objections from the Hobbs Manufacturing Company, which made mechanisms to detect slugs in nickel-operated machines. The company was not satisfied by changes made in the coin by Fraser, and in February 1913, Treasury Secretary Franklin MacVeagh decided to issue the coins despite the objections.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Buffalo_nickel',
  },
  jeffersonNickels: {
    id: '13',
    title: 'Jefferson Nickels',
    startDate: '1938',
    endDate: 'Present',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/NickelObverses.jpg/440px-NickelObverses.jpg',
    body: `<p>The Jefferson nickel has been the five-cent coin struck by the United States Mint since 1938, when it replaced the Buffalo nickel. From 1938 until 2004, the copper-nickel coin's obverse featured a profile depiction of founding father and third U.S. President Thomas Jefferson by artist Felix Schlag; the obverse design used in 2005 was also in profile, though by Joe Fitzgerald. Since 2006 Jefferson's portrayal, newly designed by Jamie Franki, faces forward. The coin's reverse is still the Schlag original, although in 2004 and 2005 the piece bore commemorative designs.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Jefferson_nickel',
  },
  olderDimes: {
    id: '14',
    title: 'Older Dimes',
    startDate: '1796',
    endDate: '1837',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/NNC-US-1820-10C-Capped_Bust.jpg/440px-NNC-US-1820-10C-Capped_Bust.jpg',
    body: `<p>The first dime to be circulated was the Draped Bust dime, in 1796. It featured the same obverse and reverse as all other circulating coins of the time, the so-called Draped Bust/Small Eagle design. This design was the work of then-Chief Engraver Robert Scot. The portrait of Liberty on the obverse was based on a Gilbert Stuart drawing of prominent Philadelphia socialite Ann Willing Bingham, wife of noted American statesman William Bingham. The reverse design is of a small bald eagle surrounded by palm and olive branches, and perched on a cloud. Since the Coinage Act of 1792 required only that the cent and half cent display their denomination, Draped Bust dimes were minted with no indication of their value.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Dime_(United_States_coin)',
  },
  seatedLibertyDimes: {
    id: '15',
    title: 'Seated Liberty Dimes',
    startDate: '1837',
    endDate: '1891',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/NNC-US-1840-10C-Seated_Liberty_%28stars%2C_no_drapery%29.jpg/440px-NNC-US-1840-10C-Seated_Liberty_%28stars%2C_no_drapery%29.jpg',
    body: `<p>Christian Gobrecht completed the design of the Seated Liberty dime, whose obverse was used with every circulating silver U.S. coin of the period. Mint Director Robert Maskell Patterson requested a new coin design, to be reminiscent of the Britannia image found on coinage of the United Kingdom. Chief Engraver William Kneass drew the original sketches, but suffered a stroke and was too ill to finish them or to oversee preparation of the dies. The task then fell to Gobrecht, who was promoted to Second Engraver.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Dime_(United_States_coin)',
  },
  barberDimes: {
    id: '16',
    title: 'Barber Dimes',
    startDate: '1892',
    endDate: '1916',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/1914_Barber_Dime_NGC_MS64plus_Obverse.png/440px-1914_Barber_Dime_NGC_MS64plus_Obverse.png',
    body: `<p>The Barber coinage consisted of a dime, quarter, and half dollar designed by United States Bureau of the Mint Chief Engraver Charles E. Barber. They were minted between 1892 and 1916, though no half dollars were struck in the final year of the series.</p><p>By the late 1880s, there were increasing calls for the replacement of the Seated Liberty design, used since the 1830s on most denominations of silver coins. In 1891, Mint Director Edward O. Leech, having been authorized by Congress to approve coin redesigns, ordered a competition, seeking a new look for the silver coins. As only the winner would receive a cash prize, invited artists refused to participate and no entry from the public proved suitable. Leech instructed Barber to prepare new designs for the dime, quarter, and half dollar, and after the chief engraver made changes to secure Leech's endorsement, they were approved by President Benjamin Harrison in November 1891. Striking of the new coins began the following January.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Barber_coinage',
  },
  mercuryDimes: {
    id: '17',
    title: 'Mercury Dimes',
    startDate: '1916',
    endDate: '1945',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/1943D_Mercury_Dime_obverse.jpg/440px-1943D_Mercury_Dime_obverse.jpg',
    body: `<p>The Mercury dime is a ten-cent coin struck by the United States Mint from 1916 to 1945. Designed by Adolph Weinman and more correctly referred to as the Winged Liberty Head dime, it gained its common name as the obverse depiction of a young Liberty, identifiable by her winged Phrygian cap, was confused with the Roman god Mercury. Weinman is believed to have used Elsie Stevens, the wife of lawyer and poet Wallace Stevens, as a model. The coin's reverse depicts a fasces, symbolizing unity and strength, and an olive branch, signifying peace.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Mercury_dime',
  },
  rooseveltDimes: {
    id: '18',
    title: 'Roosevelt Dimes',
    startDate: '1946',
    endDate: 'Present',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/2017-D_Roosevelt_dime_obverse_transparent.png/440px-2017-D_Roosevelt_dime_obverse_transparent.png',
    body: `<p>The Roosevelt dime is the current dime, or ten-cent piece, of the United States. Struck by the United States Mint continuously since 1946, it displays President Franklin D. Roosevelt on the obverse and was authorized soon after his death in 1945.</p><p>Roosevelt had been stricken with polio, and was one of the moving forces of the March of Dimes. The ten-cent coin could be changed by the Mint without the need for congressional action, and officials moved quickly to replace the Mercury dime. Chief Engraver John R. Sinnock prepared models, but faced repeated criticism from the Commission of Fine Arts. He modified his design in response, and the coin went into circulation in January 1946.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Roosevelt_dime',
  },
  twentyCentPiece: {
    id: '19',
    title: 'Twenty-cent piece',
    startDate: '1875',
    endDate: '1878',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/1876-CC_20C_%28obv%29.jpg/440px-1876-CC_20C_%28obv%29.jpg',
    body: `<p>The American twenty-cent piece is a coin struck from 1875 to 1878, but only for collectors in the final two years. Proposed by Nevada Senator John P. Jones, it proved a failure due to confusion with the quarter, to which it was close in both size and value.</p><p>In 1874, the newly elected Jones began pressing for a twenty-cent piece, which he stated would alleviate the shortage of small change in the Far West. The bill passed Congress, and mint director Henry Linderman ordered pattern coins struck. Linderman eventually decided on an obverse and reverse similar to that of other silver coins.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Twenty-cent_piece_(United_States_coin)',
  },
  olderQuarters: {
    id: '20',
    title: 'Older Quarters',
    startDate: '1796',
    endDate: '1838',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/db/Bust_dollar_obverse.jpg',
    body: `<p>In 1796, Congress responded to the almost universal dissatisfaction of the first coins (Flowing Hair dollar) and decreed a new design. As was the custom of the time, all denominations bore the same design or, in this case, the same obverse. By Congressional decree, certain features were required: The eagle, the word Liberty, stars and United States of America. It was not considered necessary to include the value of the coin since it could be discerned from its size based on the precious metal content. Thus, the half dime was the smallest silver coin (containing 1/20 of the amount of silver in a dollar) and each denomination was larger up to the silver dollar.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Quarter_(United_States_coin)',
  },
  seatedLibertyQuarters: {
    id: '21',
    title: 'Seated Liberty Quarter',
    startDate: '1838',
    endDate: '1891',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Seated_Liberty_Quarter_with_Arrows_and_Rays.jpg/400px-Seated_Liberty_Quarter_with_Arrows_and_Rays.jpg',
    body: `<p>In 1853 and 1873, the U.S. Mint changed the weight of each denomination of silver coins. Both times, arrows were added to the coins on each side of the date. These were removed from coins in 1856 and 1875, respectively. In 1853, the mint also placed rays around the eagle on the reverse of half dollars and quarters, a feature which endured for that one year only.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/United_States_Seated_Liberty_coinage',
  },
  barberQuarters: {
    id: '22',
    title: 'Barber Quarter',
    startDate: '1892',
    endDate: '1916',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/1914_Barber_Quarter_NGC_AU58_Obverse.png/440px-1914_Barber_Quarter_NGC_AU58_Obverse.png',
    body: `<p>Charles E. Barber was born in London in 1840. His grandfather, John Barber, led the family to America in the early 1850s. Both John and his son William were engravers and Charles followed in their footsteps. The Barber family initially lived in Boston upon their arrival to the United States, though they later moved to Providence to allow William to work for the Gorham Manufacturing Company. William Barber's skills came to the attention of Mint Chief Engraver James B. Longacre, who hired him as an assistant engraver in 1865; when Longacre died in 1869, William Barber became chief engraver and Charles was hired as an assistant engraver.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Barber_coinage',
  },
  standingLibertyQuarters: {
    id: '23',
    title: 'Standing Liberty quarter',
    startDate: '1916',
    endDate: '1930',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Standing_Liberty_Quarter_Type2_1924D_Obverse.png/440px-Standing_Liberty_Quarter_Type2_1924D_Obverse.png',
    body: `<p>The Standing Liberty quarter was a 25-cent coin struck by the United States Mint from 1916 to 1930. It succeeded the Barber quarter, which had been minted since 1892. Featuring the goddess of Liberty on one side and an eagle in flight on the other, the coin was designed by sculptor Hermon Atkins MacNeil.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Standing_Liberty_quarter',
  },
  washingtonQuarters: {
    id: '24',
    title: 'Washington Quarter',
    startDate: '1932',
    endDate: 'Present',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/2006_Quarter_Proof.png/440px-2006_Quarter_Proof.png',
    body: `<p>The Washington quarter is the present quarter dollar or 25-cent piece issued by the United States Mint. The coin was first struck in 1932; the original version was designed by sculptor John Flanagan.</p><p>As the United States prepared to celebrate the 1932 bicentennial of the birth of its first president, George Washington, members of the bicentennial committee established by Congress sought a Washington half dollar. They wanted to displace for that year only the regular issue Walking Liberty half dollar; instead Congress permanently replaced the Standing Liberty quarter, requiring that a depiction of Washington appear on the obverse of the new coin. The committee had engaged sculptor Laura Gardin Fraser to design a commemorative medal, and wanted her to adapt her design for the quarter. Although Fraser's work was supported by the Commission of Fine Arts and its chairman, Charles W. Moore, Treasury Secretary Andrew W. Mellon chose a design by Flanagan, and Mellon's successor, Ogden L. Mills, refused to disturb the decision.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Washington_quarter',
  },
  statehoodQuarters: {
    id: '25',
    title: 'Statehood Quarters',
    startDate: '1999',
    endDate: '2008',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/2000_NH_Proof.png/300px-2000_NH_Proof.png',
    body: `<p>The 50 State Quarters Program (Pub.L. 105–124, 111 Stat. 2534, enacted December 1, 1997) was the release of a series of circulating commemorative coins by the United States Mint. From 1999 through 2008, it featured each of the 50 U.S. states on unique designs for the reverse of the quarter.</p><p>The 50 State Quarters Program was started to support a new generation of coin collectors,[1][2] and it became the most successful numismatic program in history, with roughly half of the U.S. population collecting the coins, either in a casual manner or as a serious pursuit.[3] The U.S. federal government so far has made additional profits of $3.0 billion from collectors taking the coins out of circulation.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/50_State_Quarters',
  },
  nationalParkQuarters: {
    id: '26',
    title: 'National Park Quarters',
    startDate: '2010',
    endDate: '2021',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/2012-ATB-Quarters-Proof-Acadia.jpg/300px-2012-ATB-Quarters-Proof-Acadia.jpg',
    body: `<p>The America the Beautiful Quarters are a series of 25-cent pieces (quarters) issued by the United States Mint starting in 2010 and scheduled to continue until at least 2021. The series may be extended at the option of the Secretary of the Treasury, potentially to 2032.[1] The obverse (front) of all the coins depicts George Washington in a restored version of the original portrait used for the 1932 Washington quarter.[2] There will be five new reverse (back) designs each year (one in 2021), each depicting a national park or national site – one from each state, the District of Columbia, and each territory. The program is authorized by the America’s Beautiful National Parks Quarter Dollar Coin Act of 2008.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/America_the_Beautiful_Quarters',
  },
  olderHalfDollars: {
    id: '27',
    title: 'Older Half Dollars',
    startDate: '1794',
    endDate: '1839',
    imageUrl: 'https://www.usacoinbook.com/us-coins/flowing-hair-half-dollar.jpg',
    body: `<p>On December 1, 1794, the first half dollars, approximately 5,300 pieces, were delivered. Another 18,000 were produced in January 1795 using dies of 1794, to save the expense of making new ones.[5] Another 30,000 pieces were struck by the end of 1801. The coin had the Heraldic Eagle, based on the Great Seal of the United States on the reverse.[5] 150,000 were minted in 1804 but struck with dies from 1803, so no 1804 specimens exist, though there were some pieces dated 1805 that carried a "5 over 4" overdate.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Half_dollar_(United_States_coin)',
  },
  seatedLibertyHalfDollars: {
    id: '28',
    title: 'Seated Liberty Half Dollar',
    startDate: '1839',
    endDate: '1866',
    imageUrl: 'https://s3.amazonaws.com/ngccoin-production/us-coin-explorer-category/4478500-006o.jpg',
    body: `<p>The late 1830s were years of great ferment, progress, growth and change for the United States Mint. Steam-powered coinage made its debut in 1836. The first branch mint opened in New Orleans in 1838, and new designs were placed on all the gold and silver coins between 1837 and 1840. The technical and artistic advancements were interrelated, for it was the introduction of steam power that stimulated Mint officials to update the coinage aesthetically as well.</p>`,
    wiki: 'https://www.ngccoin.com/coin-explorer/seated-liberty-half-dollars-1839-1891-pscid-40',
  },
  barberHalfDollar: {
    id: '29',
    title: 'Barber Half Dollar',
    startDate: '1892',
    endDate: '1915',
    imageUrl: 'https://cdn.coinvalues.com/original/35/99/99/1900-barber-half-dollar-36-1409921785.jpg',
    body: `<p>1900 Barber half dollars are relatively common coins that are particularly sought after by type collectors who want a decent specimen without having to fork over large sums of cash. In fact, virtually every issue (except for the 1900 proof half) is affordable in a grade of Good, and can be commonly found in the upper grades, too.</p><p>Barber half dollar series collectors who want to keep the grades of their coins consistent from year to year within their albums may not necessarily spend much time seeking a Fine, Very Fine, or Extremely Fine specimen of a 1900 Barber half dollar if all of the other pieces in their Barber half albums are grading Good or Very Good. However, for the collector who wants a nice example of a Barber half dollar without having to spend long to find it will likely settle on a piece from 1900.</p>`,
    wiki: 'https://coinvalues.com/barber-half-dollar/1900',
  },
  walkingLibertyHalfDollar: {
    id: '30',
    title: 'Walking Liberty Half Dollar',
    startDate: '1916',
    endDate: '1947',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Walking_Liberty_Half_Dollar_1945D_Obverse.png/440px-Walking_Liberty_Half_Dollar_1945D_Obverse.png',
    body: `<p>The Walking Liberty half dollar was a silver 50-cent piece or half dollar coin issued by the United States Mint from 1916 to 1947; it was designed by Adolph A. Weinman.</p><p>In 1915, the new Mint Director, Robert W. Woolley, came to believe that he was not only allowed but required by law to replace coin designs that had been in use for 25 years. He therefore began the process of replacing the Barber coinage: dimes, quarters and half dollars, all bearing similar designs by long-time Mint Engraver Charles E. Barber, and first struck in 1892. Woolley had the Commission of Fine Arts conduct a competition, as a result of which Weinman was selected to design the dime and half dollar.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Walking_Liberty_half_dollar',
  },
  franklinHalfDollar: {
    id: '31',
    title: 'Franklin Half Dollar',
    startDate: '1948',
    endDate: '1963',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Franklin_Half_1963_D_Obverse.png/440px-Franklin_Half_1963_D_Obverse.png',
    body: `<p>The Franklin half dollar is a coin that was struck by the United States Mint from 1948 to 1963. The fifty-cent piece pictures Founding Father Benjamin Franklin on the obverse and the Liberty Bell on the reverse. A small eagle was placed to the right of the bell to fulfill the legal requirement that half dollars depict the figure of an eagle. Produced in 90 percent silver with a reeded edge, the coin was struck at the Philadelphia, Denver, and San Francisco mints. At the end of April 2016 the metal value of the $0.50 coin was approximately $6.48, an increase of approximately 1300%.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Franklin_half_dollar',
  },
  kennedyHalfDollar: {
    id: '32',
    title: 'Kennedy Half Dollar',
    startDate: '1964',
    endDate: 'Present',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/US_Half_Dollar_Obverse_2015.png/440px-US_Half_Dollar_Obverse_2015.png',
    body: `<p>The Kennedy half dollar, first minted in 1964, is a fifty-cent coin currently issued by the United States Mint. Intended as a memorial to the assassinated President John F. Kennedy, it was authorized by Congress just over a month after his death. Use of existing works by Mint sculptors Gilroy Roberts and Frank Gasparro allowed dies to be prepared quickly, and striking of the new coins began in January 1964.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Kennedy_half_dollar',
  },
  olderDollars: {
    id: '32',
    title: 'Early Dollars',
    startDate: '1794',
    endDate: '1835',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/1804_dollar_obverse.PNG/300px-1804_dollar_obverse.PNG',
    body: `<p>The Coinage Act of 1792 authorized the production of dollar coins from silver. The United States Mint produced silver dollar coins from 1794 to 1803, then ceased regular production of silver dollars until 1836. The first silver dollars, precisely 1,758 of them, were coined on October 15, 1794 and were immediately delivered to Mint Director David Rittenhouse for distribution to dignitaries as souvenirs.[10] Thereafter, until 1804, they were struck in varying quantities. There are two obverse designs: Flowing Hair (1794–1795) and Draped Bust (1795–1804). There are also two reverse designs used for the Draped Bust variety: small eagle (1795–1798) and heraldic eagle (1798–1804). Original silver dollars from this period are highly prized by coin collectors and are exceptionally valuable, and range from fairly common to incredibly rare. Due to the early practice of hand engraving each die, there are dozens of varieties known for all dates between 1795–1803.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Dollar_coin_(United_States)',
  },
  seatedLibertyDollars: {
    id: '33',
    title: 'Seated Liberty Dollar',
    startDate: '1836',
    endDate: '1873',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/NNC-US-1865-1%24-Seated_Liberty_%28no_motto%29.jpg/722px-NNC-US-1865-1%24-Seated_Liberty_%28no_motto%29.jpg',
    body: `<p>Seated Liberty dollars were introduced in 1836 and were minted in lesser quantities than the sparsely minted Gobrecht dollar that preceded it. The dollars were used in general circulation until 1873. The production of large numbers of U.S. gold coins (First $1 1848 and $20 in 1849) from the new California mines lowered the price of gold, thereby increasing the value of silver. By 1853, the value of a U.S. Silver Dollar contained in gold terms, $1.89 of silver. With the Mint Act of 1853, all U.S. silver coins, except for the U.S. silver dollar and new 3 cent coin, were reduced by 22.9% as of weight with arrows on the date to denote reduction. The U.S. silver dollar was continued to be minted in very small numbers mainly as a foreign trade to the Orient.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Dollar_coin_(United_States)',
  },
  tradeDollars: {
    id: '34',
    title: 'Trade Dollar',
    startDate: '1873',
    endDate: '1885',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/NNC-US-1873-1%24-Seated_Liberty_%28Trade_dollar%29.jpg/722px-NNC-US-1873-1%24-Seated_Liberty_%28Trade_dollar%29.jpg',
    body: `<p>The trade dollar was produced in response to other Western powers, such as Great Britain, Spain, France, and particularly Mexico, to compete with these trade coins for use in trade in Asia. American trade dollars are 90% silver and weigh 420 grains (27.2 g), which is about 0.5 g heavier than the regular circulation Seated Liberty Dollars and Morgan Dollars. Most trade dollars ended up in China during their first two years of production, where they were very successful. Many of them exhibit holes or chopmarks which are counterstamps from Asian merchants to verify the authenticity of the coins. Many trade coins of the western powers and large silver coins from China, Korea, and Japan also bear these chopmarks. While most chopmarked coins are generally worth less than those without, some of the more fascinating chopmarks can actually give the coin a modest premium.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Dollar_coin_(United_States)',
  },
  morganDollars: {
    id: '35',
    title: 'Morgan Dollar',
    startDate: '1878',
    endDate: '1904/1921',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/NNC-US-1878-CC-1%24-Morgan_dollar.jpg/722px-NNC-US-1878-CC-1%24-Morgan_dollar.jpg',
    body: `<p>Morgan silver dollars, all composed of 90% silver and 10% copper (slightly less silver than sterling silver),[15] were struck between 1878 and 1904, with a final minting in 1921.[16] The 1921-dated coins are the most common, and there exists a substantial collector market for pristine, uncirculated specimens of the rarer dates and mint marks. Morgan dollars are second only to Lincoln Cents in collector popularity. The coin is named after George T. Morgan, its designer. Morgan dollars were minted at Philadelphia (no mint mark), New Orleans ("O" mint mark), San Francisco ("S" mint mark), Carson City ("CC" mint mark), and (in 1921 only) Denver ("D" mint mark). The mint mark is found on the reverse below the wreath, above the "O" in "DOLLAR".</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Dollar_coin_(United_States)',
  },
  peaceDollars: {
    id: '36',
    title: 'Peace Dollar',
    startDate: '1921',
    endDate: '1935',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/NNC-US-1921-1%24-Peace_dollar.jpg/722px-NNC-US-1921-1%24-Peace_dollar.jpg',
    body: `<p>Introduced in December 1921 and having the same ratio of silver-to-copper as the Morgan dollar, the Peace dollar, designed by medalist Anthony de Francisci, was promulgated to commemorate the signing of formal peace treaties between the Allied forces and Germany and Austria.[17] These treaties officially ended the Allies' World War I hostilities with these two countries. In 1922 the Mint made silver dollar production its top priority, causing other denominations to be produced sparingly if at all that year. Production ceased temporarily after 1928; original plans apparently called for only a one-year suspension, but this was extended by the Great Depression. Mintage resumed in 1934, but for only two years.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Dollar_coin_(United_States)',
  },
  eisenhowerDollars: {
    id: '37',
    title: 'Eisenhower Dollar',
    startDate: '1971',
    endDate: '1978',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/1974S_Eisenhower_Obverse.jpg/440px-1974S_Eisenhower_Obverse.jpg',
    body: `<p>The Eisenhower dollar is a one-dollar coin issued by the United States Mint from 1971 to 1978; it was the first coin of that denomination issued by the Mint since the Peace dollar series ended in 1935. The coin depicts President Dwight D. Eisenhower on the obverse, with both sides designed by Frank Gasparro.</p><p>In 1965, because of rises in bullion prices, the Mint began to strike copper-nickel clad coins instead of silver. No dollar coins had been issued in thirty years, but beginning in 1969, legislators sought to reintroduce a dollar coin into commerce. After Eisenhower died that March, there were a number of proposals to honor him with the new coin. While these bills generally commanded wide support, enactment was delayed by a dispute over whether the new coin should be in base metal or 40% silver. In 1970, a compromise was reached to strike the Eisenhower dollar in base metal for circulation, and in 40% silver as a collectible. President Richard Nixon, who had served as vice president under Eisenhower, signed legislation authorizing mintage of the new coin on December 31, 1970.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Eisenhower_dollar',
  },
  susanDollars: {
    id: '38',
    title: 'Susan B. Anthony Dollar',
    startDate: '1979',
    endDate: '1981/1999',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/1981-S_SBA%24_Type_Two_Deep_Cameo.jpg/950px-1981-S_SBA%24_Type_Two_Deep_Cameo.jpg',
    body: `<p>The Susan B. Anthony dollar is a United States dollar coin minted from 1979 to 1981, when production was suspended due to poor public acceptance, and then again in 1999. Intended as a replacement for the cumbersome Eisenhower dollar, the new smaller one dollar coin went through testing of several shapes and compositions, but all were opposed by the vending machine industry, a powerful lobby affecting coin legislation. Finally, a round planchet with an eleven-sided inner border was chosen for the smaller dollar.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Susan_B._Anthony_dollar',
  },
  sacagaweaDollars: {
    id: '39',
    title: 'Sacagawea Dollar',
    startDate: '2000',
    endDate: 'Present (Collectors only)',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fe/Sacagawea_dollar_obverse.png',
    body: `<p>The Sacagawea dollar (also known as the "golden dollar") is a United States dollar coin that has been minted every year since 2000, although not released for general circulation from 2002 to 2008 and again from 2012 onward due to its general unpopularity with the public and low business demand for the coin. These coins have a copper core clad by manganese brass, giving them a distinctive golden color. The coin features an obverse by Glenna Goodacre. From 2000 to 2008, the reverse featured an eagle design by Thomas D. Rogers. Since 2009, the reverse of the Sacagawea dollar has been changed yearly, with each design in the series depicting a different aspect of Native American cultures.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Sacagawea_dollar',
  },
  presidentialDollars: {
    id: '40',
    title: 'Presidential Dollars',
    startDate: '2007',
    endDate: '2016',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/26_Theodore_Roosevelt_2000.png',
    body: `<p>The Presidential $1 Coin Program (Pub.L. 109–145, 119 Stat. 2664, enacted December 22, 2005), was the release by the United States Mint of $1 coins with engravings of relief portraits of U.S. presidents on the obverse and the Statue of Liberty on the reverse.</p><p>From 2007 to 2011, presidential $1 coins were minted for circulation in large numbers, resulting in a large stockpile of unused $1 coins. From 2012 to 2016, new coins in the series were minted only for collectors.</p>`,
    wiki: 'https://en.wikipedia.org/wiki/Presidential_$1_Coin_Program',
  }
}

export {
  issueData
}